name: Release

on:
  push:
    branches: ['master']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
